readthedocsext/theme/templates/gold/subscription_detail.html

Close `div` properly. Otherwise, the footer looks weird.

Template: gold membership

---

readthedocsext/theme/templates/projects/import_base.html
readthedocsext/theme/templates/projects/import_basics.html
readthedocsext/theme/templates/projects/import_extra.html
readthedocsext/theme/templates/projects/import_form.html
readthedocsext/theme/templates/semantic-ui/uni_form.html

- Make the search more obvious it is a search
- Drop the mention of syncing repositories down to the bottom of the page. This should be a last resort in most cases, but still needed UX
- Tune the copy to point the user to "search for a project", instead of instructions on not finding a repository
- Tune some of the dynamic elements used in the search results
- Unify project creation columns, layout, and base form
- Some changes related to #166 and #185
[Screencast from 2023-07-07 12-41-09.webm](https://github.com/readthedocs/ext-theme/assets/1140183/fc05da83-08d7-4ba3-bae5-fe01eb2b2408)
Closes #150

Tune project creation layout and UI

---

readthedocsext/theme/templates/builds/build_detail.html
readthedocsext/theme/templates/builds/includes/build_name.html
readthedocsext/theme/templates/builds/partials/build_list.html

This addresses a few issues from #158. The build name used on the build
listing and build detail page both differed prior, and didn't mention
the version name consistently.
- Build detail page just used the build pk
- Build listing page listed all versions as "Version {{ version_name }}",
even pull request builds, which were "Version 1234" in the build
listing
Additionally, this adds some hierarchy to the build detail page, showing
an additional layer of nesting for both the version (links to a filtered
version listing) and the build list (links to a filtered build listing).
Closes #158
Build listing:
Build detail:
UX:
[Screencast from 2023-07-11 12-43-30.webm](https://github.com/readthedocs/ext-theme/assets/1140183/0757c546-7d77-437b-bfcb-ab9addfccc7a)

Add unified build list and build detail page title for builds

---

readthedocsext/theme/templates/projects/addons_form.html
readthedocsext/theme/templates/projects/edit_base.html

Show a small form to the user where they can enable/disable the new beta addons on their project.
* Closes #212
* Requires https://github.com/readthedocs/readthedocs.org/pull/10733

Addons: allow users to opt-in into the beta addons

---

readthedocsext/theme/templates/projects/integration_webhook_detail.html

Same as https://github.com/readthedocs/readthedocs.org/pull/10801

Integrations: don't link webhooks to beta domain

---

readthedocsext/theme/templates/projects/projectrelationship_list.html

`subproject` is a Project object, not a relationship object.
Can be tested with https://beta.readthedocs.org/dashboard/stsewd-demo/subprojects/

Fix subprojects list template

---

readthedocsext/theme/templates/projects/translation_list.html

Port of https://github.com/readthedocs/readthedocs.org/pull/10766

Translations: add check for supported versioning schemes

---

webpack.config.mjs

This is super handy, it will reload dev server connected pages when you
save an HTML template. No more switching windows and reloading the tab!

Add a listener for html files to web pack

---

readthedocsext/theme/templates/builds/build_list.html
readthedocsext/theme/templates/builds/partials/build_list.html

This consolidates all of the build list checks for `is_admin:project`
into a single template variable for now. This replicates what we're
doing at the view level in other views.
Ongoing discussion for a long term approach is at #49
- Refs #128

Improve performance of build list view

---

readthedocsext/theme/templates/includes/crud/table_list.html

Previously, a large queryset would cause a view to timeout, as the
conditional `if objects` ends up inspecting the entire queryset for
some version of truthiness. Instead, a more explicit check for both
empty arrays and empty querysets avoids this overhead.
- Closes #209

Improve performance of table listing for large querysets

---

readthedocsext/theme/templates/organizations/includes/feature_disabled.html
readthedocsext/theme/templates/organizations/settings/security_log.html
readthedocsext/theme/templates/projects/partials/edit/domain_list.html
readthedocsext/theme/templates/projects/partials/edit/search_query_list.html
readthedocsext/theme/templates/projects/partials/edit/traffic_list.html

This template is used in a few views to point to a subscription upgrade. For
now, it either is replacing UI or just the top menu buttons in a listing UI.
Screenshots in #56 
- Fixes #56

Add org feature disabled template

---

readthedocsext/theme/templates/projects/partials/edit/redirect_list.html

Matches https://github.com/readthedocs/readthedocs.org/pull/10881/.
Applied the same code we have for automation rules.
There are some new options that we may want to include in the UI, like status code, description, and if the redirect is enabled/disabled. We can also think about implementing some nice drag and drop in addition to the arrow buttons.

Redirects: match recent improvements

---

readthedocsext/theme/templates/projects/settings_advanced_form.html

We removed the crispy `Layout` in
https://github.com/readthedocs/readthedocs.org/pull/11036 and there is no need to render the form using the template tag as we were doing.
This matches the changes done in the linked PR.

Admin: render "advanced form" with crispy filter

---

readthedocsext/theme/templates/includes/utils/messages.html
readthedocsext/theme/templates/organizations/partials/header.html
readthedocsext/theme/templates/projects/partials/header.html

Render notifications attached to these objects.
This is the first pass of this work and there are some things we need to make decisions and improve.
- Where (what pages) these notifications should render?
- How "global" they should be considered?
Note we are rendering these notifications in the template for now, but in the future they will be rendered using the APIv3: #259
Closes #260

Notifications: show attached to `User`, `Project` and `Organization`

---

readthedocsext/theme/templates/includes/elements/chips/build.html

When versions are removed, the builds remain with a `build.version = None`,
along with some additional attributes on the Build instance (for example
`build.version_name`).
This bug affected any display that listed projects/versions that listed
the most recent build.
- Fixes readthedocs/readthedocs.org#11061

Use build.version_name first, in case build.version is None

---

readthedocsext/theme/templates/builds/build_detail.html
readthedocsext/theme/templates/builds/includes/build_name.html

This uses the build methods to get version name/slug instead of expecting
Build.version to always be a valid relationship.
Changes are in 306dd40

Fix issues stemming from builds with null versions

---

readthedocsext/theme/templates/projects/partials/project_create_automatic.html

Originally raised here:
- https://github.com/readthedocs/readthedocs.org/issues/10842
I wonder if the API data source changed at some point? Either way, the
effect was that the project create form step would submit and not work
(though not raise a validation error either).
I finally noticed this locally today, and in the deploy while testing. I
included a fix for the default branch name, that wasn't auto populating
either.
- Fixes https://github.com/readthedocs/readthedocs.org/issues/10842

Fix project create wizard form step

---

readthedocsext/theme/templates/builds/build_detail.html

This adds a notification to just the detail view that links directly back to the same page on the normal dashboard.
- Requires https://github.com/readthedocs/readthedocs.org/pull/11208
- Fixes #284
- Refs https://github.com/readthedocs/readthedocs.org/issues/11209

Add build detail notification to switch back to the normal dashboard

---

readthedocsext/theme/templates/account/login.html
readthedocsext/theme/templates/socialaccount/snippets/provider_list.html

Normal login
Login restricted to one provider
Login when trying to access a documentation page
Closes https://github.com/readthedocs/ext-theme/issues/276

Port CAS related changes

---

.circleci/config.yml
docs/api/js/webcomponents.rst

I did a local run with `pre-commit run --all-files` (the changes on the .rst file come from that), but on CI I'm just checking the last diff as the pre-commit doc recommend.
pre-commit makes use of node internally, so node is needed in that step, also merging the node and python lint jobs into one.
Closes https://github.com/readthedocs/ext-theme/issues/268

CI: Run pre-commit

---

readthedocsext/theme/templates/socialaccount/snippets/provider_list.html

We didn't catch this in #325, but the comment is a single line comment,
not a multiline comment.

Fix sign up comment

---

readthedocsext/theme/templates/errors/dashboard/401.html
readthedocsext/theme/templates/errors/dashboard/403.html
readthedocsext/theme/templates/errors/dashboard/404.html
readthedocsext/theme/templates/errors/dashboard/410.html
readthedocsext/theme/templates/errors/dashboard/429.html
readthedocsext/theme/templates/errors/dashboard/4xx.html
readthedocsext/theme/templates/errors/dashboard/504.html
readthedocsext/theme/templates/errors/dashboard/5xx.html
readthedocsext/theme/templates/errors/dashboard/base.html

This ports in the initial error pages from our website so that the dashboard
error pages look polished. This does not yet update the documentation error
pages, which I am considering the next batch of work afterwards.
Changes here:
- Organizes dashboard errors into an isolated path. There will be a separate
path for less branded error pages for Proxito.
- Error pages are consolidated to all match styles. For now the styles are
fairly minor, but I'd want to return to these later. Our error pages have
always been goofball pages, and I appreciate that.
- I used fallback error templates in case I missed anything, it wouldn't be hard
to eventually drop the fallback templates if we want.
- The 404 page has some slight additional logic to point to the login view for
now, with `?next`. This …

Add dashboard error pages

---

readthedocsext/theme/templates/builds/partials/build_list.html
readthedocsext/theme/templates/includes/elements/chips/version.html

Protect against null build versions, there is nothing to show in these
cases.
- Fixes #251

Conditionally inject build version chip embed

---

readthedocsext/theme/templates/invitations/partials/invitation_list.html

Instead of doing this at the existing `is_admin` filter, use a new filter specifically for this template. Supersedes https://github.com/readthedocs/readthedocs-corporate/pull/1793
- Requires https://github.com/readthedocs/readthedocs.org/pull/11368
- Fixes #354

Use invitation filter instead of is_admin filter

---

readthedocsext/theme/templates/builds/partials/build_list.html
readthedocsext/theme/templates/builds/partials/version_list.html
readthedocsext/theme/templates/includes/crud/table_list.html
readthedocsext/theme/templates/organizations/partials/members_list.html
readthedocsext/theme/templates/organizations/partials/organization_list.html
readthedocsext/theme/templates/organizations/partials/owners_list.html
readthedocsext/theme/templates/organizations/partials/team_list.html
readthedocsext/theme/templates/organizations/partials/team_member_list.html
readthedocsext/theme/templates/projects/partials/project_list.html

- Split up placeholder content into onboarding when no objects exist
yet, and some copy for when there are objects but they are just all
filtered out
- Fix placeholder buttons that were not linking anywhere
- Guide away from organization creation a little. See https://github.com/readthedocs/readthedocs.org/issues/11356
----
- Fixes: #230

Add better placeholder content for views with filters

---

MANIFEST.in

For some weird reason, graft isn't including some directories in the final distribution (organizations/settings for example). Using recursive-include fixes that problem,
not sure if this is a bug with setuptools or something else.

Fix distribution not including some templates

---

readthedocsext/theme/templates/projects/partials/project_list.html

Show the elipsis as disabled when the user doesn't have permissions. Follows the same pattern with the documentation/book icon that is disabled when there is no successful build yet.

Projects: disable elipsis when user doesn't have permissions

---

readthedocsext/theme/templates/projects/partials/header.html

Simple and small fix for this issue.
We should still decide what to do at the db level still.
Closes #358

Project: use `zh-cn` if the language code is the unsupported `zh`

---

readthedocsext/theme/templates/projects/partials/edit/search_query_list.html

Improve how we show the results the query returned and also how many times users have searched for that particular query)

Search Analytics: show results and queries

---

readthedocsext/theme/templates/projects/import_config.html

I used tabs to show different examples of YAML files, as suggested in #184. It looks great for an initial interactive approach.
I like the tabs over the dropdown because it gives the user a clear idea there are more than Sphinx and MkDocs tools supported, which is a good marketing strategy, in my opinion.
It also adds an "Others" option that's more generic and shows how to use `build.commands` in a generic way: install dependencies, build, copy assets under `$READTHDOCS_OUTPUT` directory.
* Closes #184
* Closes https://github.com/readthedocs/readthedocs.org/issues/10352

Add project: show more `yaml` examples

---

readthedocsext/theme/templates/projects/partials/project_list.html

projects_manage is a redirect.
https://github.com/readthedocs/readthedocs.org/blob/c0307db5b55106aa07d6b432117f622e0c79fbb3/readthedocs/projects/urls/private.py#L75-L81

Link to project detail using projects_detail

---

readthedocsext/theme/templates/projects/import_config.html

I removed all the other `build.tools` that are not related with the current example.
The only thing that I didn't remove yet is the part that talks about pinning the dependencies because I think most users will require that anyways.
Related https://github.com/readthedocs/ext-theme/issues/373

Remove comments from examples when adding projects

---

readthedocsext/theme/templates/support/error.html

Tell people to contact us via email if the form fails for any reason.
Closes https://github.com/readthedocs/readthedocs.org/issues/8314

Support: expose our email in case the form fails

---

readthedocsext/theme/templates/projects/addons_form.html

This blog post has a really good overview about what Addons are and how to enable them. In the future we will want to change these links by the official addons docs, but we are not there yet.

Help topics: add latest addons blog post

---

readthedocsext/theme/templates/account/login.html
readthedocsext/theme/templates/account/signup.html

Currently this reads "Sign in" when the user is signing up. I'm guessing this was a mistake.
The sign in page still says "Sign in with".

Use sign up instead of sign in when signing up

---

readthedocsext/theme/templates/organizations/partials/header.html

Use `readthedocs-notification-list` Web Component to list all the notifications related with the organization.
Closes #359

Notifications: use the web component for organization

---

readthedocsext/theme/templates/projects/base_dashboard.html

This PR copies the same pattern we have in other places (eg. project's settings) using "Help topics". I copied it from there because it renders nicer than the one we had and also to keep consistency between them all.

Help topics on base dashboard

---

.djlintrc
.pre-commit-config.yaml
readthedocsext/theme/templates/base.html

Djhtml is inconsistent and doesn't provide any linting checks. Running djlint instead, and through pre-commit on a per-file basis, gives a fairly easy way to migrate to stronger formatting/linting on template code.
- Fixes #329

Try djlint instead of djhtml

---

readthedocsext/theme/templates/includes/elements/chips/project.html
readthedocsext/theme/templates/includes/footer.html
readthedocsext/theme/templates/projects/partials/header.html
readthedocsext/theme/templatetags/ext_theme_tags.py

We keep returning 500 on projects with `zh`.
This another interation on this fix for now.
Sentry https://read-the-docs.sentry.io/issues/5066249292/
Related #370

Project: use a custom template filter to avoid zh languages

---

readthedocsext/theme/templates/allauth/layouts/base.html

The allauth templates are overwriting the base templates block:
* https://github.com/readthedocs/ext-theme/blob/main/readthedocsext/theme/templates/allauth/layouts/base.html#L3 is overriding
* https://github.com/readthedocs/ext-theme/blob/main/readthedocsext/theme/templates/base.html#L63
Fixes https://github.com/readthedocs/ext-theme/issues/425

Add notifications block to AllAuth templates

---

.djlint_rules.yaml
.djlintrc

Use max_line_length=80, this only controls when attributes/blocks are
wrapped. This setting is why nicer block formatting is sometimes
condensed down to single lines.
The lint rule is for catching wildcard load imports.

Tune djlint configuration

---

readthedocsext/theme/templates/account/signup.html
readthedocsext/theme/templates/builds/build_detail.html
readthedocsext/theme/templates/homepage.html
readthedocsext/theme/templates/includes/footer.html
readthedocsext/theme/templates/profiles/partials/token_list.html
readthedocsext/theme/templates/profiles/private/advertising_profile.html
readthedocsext/theme/templates/profiles/private/security_log.html
readthedocsext/theme/templates/projects/environmentvariable_list.html
readthedocsext/theme/templates/projects/integration_webhook_detail.html
readthedocsext/theme/templates/projects/onboard_detail.html
readthedocsext/theme/templates/projects/onboard_import.html
readthedocsext/theme/templates/projects/partials/edit/automation_rule_list.html
readthedocsext/theme/templates/projects/partials/edit/domain_list.html
readthedocsext/theme/templates/projects/partials/edit/environment_variable_list.html
readthedocsext/theme/templates/projects/partials/edit/integration_list.html
readthedocsext/theme/templates/projects/partials/edit/keys_list.html
readthedocsext/theme/templates/projects/partials/edit/notification_email_list.html
readthedocsext/theme/templates/projects/partials/edit/redirect_list.html
readthedocsext/theme/templates/projects/partials/edit/search_query_list.html
readthedocsext/theme/templates/projects/partials/edit/subproject_list.html
readthedocsext/theme/templates/projects/partials/edit/temporary_access_list.html
readthedocsext/theme/templates/projects/partials/edit/traffic_list.html
readthedocsext/theme/templates/projects/partials/edit/translation_list.html
readthedocsext/theme/templates/projects/partials/edit/webhook_list.html
readthedocsext/theme/templates/projects/partials/project_create_automatic.html
readthedocsext/theme/templates/projects/partials/project_list.html
readthedocsext/theme/templates/socialaccount/partials/social_account_list.html
readthedocsext/theme/templates/support/index.html
readthedocsext/theme/templates/support/success.html

This is based on a feedback we received from a user.
As a general rule, we should use `target=_blank` for all the links that go
_outside_ the dashboard.
**There is a lot of lint changes**. I split the work into different commits to make it easier to review.

Use target="_blank" for external links

---

readthedocsext/theme/templates/profiles/private/advertising_profile.html

Tests are broken on .org https://app.circleci.com/pipelines/github/readthedocs/readthedocs.org/10773/workflows/73ad0168-daed-48b0-8d7e-fd268fbceb63/jobs/27086
Maybe the fix is as simple as this?
> django.template.exceptions.TemplateSyntaxError: Invalid block tag on line 11: 'endblock', expected 'endblock' or 'endblock profile_admin_advertising'. Did you forget to register or load this tag?

Try to fix tests

---

readthedocsext/theme/templates/projects/import_base.html
readthedocsext/theme/templates/projects/import_config.html

Idea we talked in the Book Club.
I'm opening the PR here to continue improving this idea.

Add project: change copy for "Finish" button

---

readthedocsext/theme/templates/account/login.html

The new dashboard doesn't work for granting access to docs pages yet.

Link to old dashboard for SAML login

---

readthedocsext/theme/templates/socialaccount/snippets/provider_list.html

Bitbucket doesn't allow more than one callback URL for their OAuth app, so we are redirecting users to the old dashboard for now.
closes https://github.com/readthedocs/readthedocs-ops/issues/1509

OAuth: redirect Bitbucket to the old dashboard

---

readthedocsext/theme/templates/acl/shared_password_required.html
readthedocsext/theme/templates/proxito/base.html

This is a simple placeholder until we have
the base templates for proxito ready.
We need this template, so tests from https://github.com/readthedocs/readthedocs-corporate/pull/1807 pass.
Ref https://github.com/readthedocs/ext-theme/issues/393

Proxito: add template for password protected docs

---

readthedocsext/theme/templates/projects/domain_form.html

This is the initial work required -- not tuned.
- Bring back the notification explaining that a CNAME has to be added in the DNS
- Bring back the notification about the validation process ended
My goal here is to give users the information they need to setup the domain. However, I think this page could get benefit from some extra work/style. Baby steps.
Closes #449

Domain: show notifications for configuration

---

readthedocsext/theme/templates/account/email_confirm.html
readthedocsext/theme/templates/account/login.html
readthedocsext/theme/templates/account/password_reset.html
readthedocsext/theme/templates/account/password_reset_done.html
readthedocsext/theme/templates/account/password_reset_from_key.html
readthedocsext/theme/templates/account/password_reset_from_key_done.html
readthedocsext/theme/templates/account/saml.html
readthedocsext/theme/templates/allauth/layouts/entrance.html
readthedocsext/theme/templates/allauth/layouts/manage.html
readthedocsext/theme/templates/errors/proxito/base.html
readthedocsext/theme/templates/proxito/base.html

This uses the entrance/manage base pattern from Allauth to provide two base templates:
- Any template using base_entrance.html will use the Proxito style base template, which drops the header/footer from the application. CSS/JS is still used however
- An application styled base_manage.html for pages that are more clearly account management templates
Some missing templates were not styled and were adapted from Allauth templates.
- Fixes #435
- Fixes #427
- Refs #462

Use proxito base templates for Allauth account/socialaccount templates

---

readthedocsext/theme/templates/socialaccount/authentication_error.html
readthedocsext/theme/templates/socialaccount/signup.html

I added a couple of the templates that exist in Allauth but not here.
- Fixes #462
- Requires #479

Add missing socialaccount templates

---

readthedocsext/theme/templates/projects/addons_form.html

This is effectively the same as using Crispy Layout API, but allows for authoring more/richer HTML content in the tabs as we need. For example, we might want to include nicer placeholder segments or images in the tabs.
One improvement might be a way to define the fields for each tab in the Form instance, so that we don't have to hardcode field names in templates, but instead iterate over each field in `form.fieldsets.flyout`, or similar.
- Fixes #293
[Screencast from 2024-09-11 17-16-16.webm](https://github.com/user-attachments/assets/8998bd11-5930-4e67-adde-eecf6557025e)

Use multiple tabs for addons configuration page

---

readthedocsext/theme/templates/account/base_reauthenticate.html
readthedocsext/theme/templates/account/password_change.html
readthedocsext/theme/templates/account/reauthenticate.html
readthedocsext/theme/templates/mfa/authenticate.html
readthedocsext/theme/templates/mfa/base_manage.html
readthedocsext/theme/templates/mfa/index.html
readthedocsext/theme/templates/mfa/reauthenticate.html
readthedocsext/theme/templates/mfa/recovery_codes/index.html
readthedocsext/theme/templates/mfa/totp/activate_form.html
readthedocsext/theme/templates/profiles/base_edit.html

I placed this as a subpage under the profile "Security" admin dashboard
for now, though this is still not linked anywhere.
The entrance pages use the minimal login base templates, while the
management pages use the user profile edit base as a base template, so
that all of the management functions appear under the user profile
admin.
- Fixes #443
[Screencast from 2024-09-11 14-07-31.webm](https://github.com/user-attachments/assets/efae06c4-c14f-448f-a496-7f39fbe370dd)

Add templates for Allauth MFA

---

readthedocsext/theme/templates/acl/shared_password_required.html

Uses same base as Allauth views, which is a derivate of the Proxito base
view already. This fixes some copy and elements, and addresses the link
to log in with other methods at least temporarily.
- Fixes #393

Update password auth view

---

readthedocsext/theme/templates/includes/crud/table_list.html

I found that we are using `mini` "Teams" listing, but `small` on "Projects"
listing. I'm changing it to `small` in "Teams" for consistency.
Take a look at
* https://app.readthedocs.com/organizations/read-the-docs-qa/teams/
* https://app.readthedocs.com/organizations/read-the-docs-qa/

Teams: use small for menu to match other places

---

readthedocsext/theme/templates/includes/crud/table_list.html

From #486, linting introduced a missing template tag

Fix exception with missing pagination tag

---

readthedocsext/theme/templatetags/ext_theme_tags.py

Django tags apparently don't work in format strings 🙃

Fix dynamic import path

---

readthedocsext/theme/templatetags/ext_theme_tags.py

This is causing 500s on the dashboard,
so just logging it in Sentry for now instead of 500ing.
Refs https://read-the-docs.sentry.io/issues/5642802576/?project=148442&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&statsPeriod=24h&stream_index=0

Be more defensive in our language code display

---

readthedocsext/theme/templates/account/email.html
readthedocsext/theme/templates/account/partials/email_list.html
readthedocsext/theme/templates/gold/partials/projects_list.html
readthedocsext/theme/templates/organizations/partials/owners_list.html
readthedocsext/theme/templates/projects/partials/edit/automation_rule_list.html
readthedocsext/theme/templates/projects/partials/edit/environment_variable_list.html
readthedocsext/theme/templates/projects/partials/edit/integration_list.html
readthedocsext/theme/templates/projects/partials/edit/notification_email_list.html
readthedocsext/theme/templates/projects/partials/edit/redirect_list.html
readthedocsext/theme/templates/projects/partials/edit/subproject_list.html
readthedocsext/theme/templates/projects/partials/edit/temporary_access_list.html
readthedocsext/theme/templates/projects/partials/edit/translation_list.html
readthedocsext/theme/templates/projects/partials/edit/user_list.html
readthedocsext/theme/templates/projects/partials/edit/webhook_list.html

The remove_button partial expects a variable named `content_text`, but we were passing `context_text` instead. It was working before because all variables from the current template are passed to the partial.

Rename context_text to content_text

---

readthedocsext/theme/templates/projects/addons_form.html

Instead of showing one checkbox to enable "Show notification on latest and non-stable versions" we have two checkboxes now:
- "Show notification on latest version"
- "Show notification on non-stable versions"
Requires https://github.com/readthedocs/addons/pull/414
Requires https://github.com/readthedocs/readthedocs.org/pull/11718

Addons: split single checkbox into two

---

readthedocsext/theme/templates/projects/import_base.html

This adds a button "I need help" that shows a modal with more instructions about how to add the required `.readthedocs.yaml`.
I will need some help with the copy/instructions we want to show the customer.
Closes https://github.com/readthedocs/ext-theme/issues/445

Add project: modal with instructions about adding a config file

---

readthedocsext/theme/templates/projects/import_config.html

Reference https://github.com/readthedocs/readthedocs.org/pull/11742

Add project: update examples with newer build tools versions

---

readthedocsext/theme/templates/403_csrf.html
readthedocsext/theme/templates/errors/dashboard/403_csrf.html

This is the default from Django:
https://docs.djangoproject.com/en/5.1/ref/settings/#csrf-failure-view
I'm actually not sure where these error templates are configured to be used, so not 100% sure it will work.
However, we currently show the default 403 template in prod, which is bad:

Add 403 CSRF template

---

readthedocsext/theme/templates/403_csrf.html
readthedocsext/theme/templates/errors/proxito/403_csrf.html

We do trigger CSRF errors from Proxito, so use the more minimal error page.
Fixes https://read-the-docs.sentry.io/issues/6108273096/?project=148442&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&statsPeriod=14d&stream_index=7

Extend CSRF 403 from Proxito

---

readthedocsext/theme/templates/base.html
readthedocsext/theme/templates/projects/base_dashboard.html

Remove weird spacing from titles

---

readthedocsext/theme/templates/organizations/partials/members_list.html
readthedocsext/theme/templates/organizations/partials/team_member_list.html

The fixes to the team listing page caused new issues on the member listing page, for the same reasons. Both views now show the same -- user full name if available with username underneath, or if no full name just the username.
Last attempt was #546 but this removed the display name on the member listing, which was using the correct attribute names already. readthedocs/readthedocs.org#11861 fixes this discrepancy.
- Requires readthedocs/readthedocs.org#11861

Fix member listing page

---

readthedocsext/theme/templates/projects/addons_form.html

Required by https://github.com/readthedocs/addons/issues/434

Addons: add "flyout position" to the form

---

readthedocsext/theme/templates/projects/version_form.html

Ref https://github.com/readthedocs/readthedocs.org/pull/11930

Warn about changing a version slug

---

readthedocsext/theme/templates/projects/addons_form.html

We don't expose it to all the users yet, but we want to expose it for those that we already enabled it on the Django Admin.

Filetreediff: expose it for users that have it enabled

---

readthedocsext/theme/templates/account/login.html

The form itself will be in charge of redirecting to the old dashboard if needed.
ref https://github.com/readthedocs/readthedocs-corporate/pull/1954

SAML: don't link to the old dashboard

---

readthedocsext/theme/templates/projects/partials/announcements/new-dashboard.html

This is just updating the copy. Eventually we should just remove this
block entirely.

Drop legacy dashboard from dashboard announcement

---

readthedocsext/theme/templates/profiles/partials/github_app_project_list.html
readthedocsext/theme/templates/profiles/partials/github_app_project_migrated_list.html
readthedocsext/theme/templates/profiles/partials/github_app_target_list.html
readthedocsext/theme/templates/profiles/private/migrate_to_gh_app.html

- Use partials instead of one off listings
- Reduce text and move to UI elements
- Compact information in table listing and move warnings about installation/migration issues to the button. Show button as disabled when next steps are not possible.
- Use a partial for the second list at the bottom
Relevant commit is be49f17
This addresses issues with the UI being quite cramped and elements overlapping/wrapping and the UI generally having a bit too much text.
I did not test if pagination would work, I assume not. I don't love having two lists on this UI, it would be better as a singular list instead of two. This would require reworking the logic used, namely the use of dataclasses for each list of objects.

Clean up migration project listing

---

readthedocsext/theme/templates/profiles/partials/github_app_target_list.html
readthedocsext/theme/templates/profiles/private/migrate_to_gh_app.html

- Use less blocks of text and more UI elements
- Use common listing partial for list of installation targets instead of one-off listing structure. This matches the styling we have on all other list of objects as well.
- Use placeholder content area in listing instead of extra blocks of text
Note: I couldn't quite test the install button as it gives me a 404.

Improve GHA installation tab

---

docs/api/stylesheets.rst
docs/conf.py
docs/docext.py
docs/index.rst
readthedocsext/theme/templates/includes/header.html
readthedocsext/theme/templates/projects/partials/project_create_automatic.html
setup.cfg
src/sui/themes/rtd-application/collections/table.overrides
src/sui/themes/rtd-application/elements/image.overrides
src/sui/themes/rtd-application/globals/site.overrides
tox.ini

This adds some more documentation sourced from our theme styles,
including the pattern we've been using to replace the Knockout
``visible`` binding with a pattern that doesn't need inline styles.
https://read-the-docs-docs-landing--585.com.readthedocs.build/projects/ext-theme/en/585/api/stylesheets.html

Some docs on stylesheets and update linting fix to KO hidden pattern

---

readthedocsext/theme/templates/projects/partials/project_create_automatic.html

The other page where we talk about private repos is https://docs.readthedocs.com/platform/stable/guides/importing-private-repositories.html, but feels like the commercial page is better suited here.

Link to docs when project is private

---

readthedocsext/theme/templates/projects/partials/header.html

With the conditional view docs button on the right, the settings button
is not always on the right-most button -- it jumps around. Make
temporary view docs button the left most instead, it makes the
disappearing button less obvious.
Also fixes template issues that weren't addressed.

Keep settings button in the same place always

---

readthedocsext/theme/templates/profiles/partials/github_oauth_disconnect_list.html
readthedocsext/theme/templates/profiles/partials/github_oauth_revoke_list.html
readthedocsext/theme/templates/profiles/private/migrate_to_gh_app.html

The revoke and disconnect options are not available during the beta, so users can use the old button to log in without any problems. They can still do this from the social accounts list, but if they do so, next time they log in will be redirected to the correct login page, so.
Ref https://github.com/readthedocs/meta/issues/187

GitHub App: open beta

---

readthedocsext/theme/templates/profiles/private/migrate_to_gh_app.html

If a user has lots of projects, it's hard to see this option without having to scroll all the way down. But looks weird having this big section before the listing, maybe something like having a "migrate all" link to the actual section is better?

GitHub App migration page: put migrate all first

---

readthedocsext/theme/templates/projects/version_form.html

This is implements the idea 4) from
https://github.com/readthedocs/readthedocs.org/issues/11978 as a first step.
However, we can get fancier here and automate this creation somehow if we want. There are more ideas for UX in that issue.

Link to redirect creation page when editing a version

---

readthedocsext/theme/templates/includes/crud/table_list.html
readthedocsext/theme/templatetags/ext_theme_tags.py

If the object to check was a queryset, exist would be called twice. Instead of dealing with checks in the template, I'm just using a filter.
Tests on .org will need to be updated after this is merged to reduce the expected queries.

Avoid calling .exists twice in the same query

---

readthedocsext/theme/templates/includes/crud/pagination.html

Replaces https://github.com/readthedocs/ext-theme/pull/640

Make pagination menu wrapping
