- readthedocsext/theme/templates/gold/subscription_detail.html
- readthedocsext/theme/templates/gold/subscription_form.html
- readthedocsext/theme/templates/profiles/private/advertising_profile.html
Corresponding change to https://github.com/readthedocs/readthedocs.org/pull/10459.
> Update gold templates to reflect ad-free reality

- readthedocsext/theme/templates/organizations/member_list.html
- readthedocsext/theme/templates/organizations/organization_detail.html
- readthedocsext/theme/templates/organizations/partials/has_sso/members_list.html
- readthedocsext/theme/templates/organizations/partials/has_sso/project_list.html
- readthedocsext/theme/templates/organizations/partials/has_sso/team_list.html
- readthedocsext/theme/templates/organizations/partials/organization_list.html
- readthedocsext/theme/templates/organizations/partials/project_list.html
- readthedocsext/theme/templates/organizations/team_list.html
- readthedocsext/theme/templates/projects/partials/project_list.html
- Resolves #227 
[Screencast from 2023-12-13 20-08-52.webm](https://github.com/readthedocs/ext-theme/assets/1140183/b24b07c5-7164-404d-a9bd-a33248139121)
> Add SSO conditionals back to organization templates

- readthedocsext/theme/templates/includes/footer.html
Fixes https://github.com/readthedocs/ext-theme/issues/264
> Hide "Sponsored by" section on commercial

- readthedocsext/theme/templates/projects/version_form.html
Closes https://github.com/readthedocs/ext-theme/issues/275
> Version form: warn about deactivating a version

- readthedocsext/theme/templates/projects/edit_base.html
- readthedocsext/theme/templates/projects/project_advanced.html
- readthedocsext/theme/templates/projects/settings_advanced_form.html
- readthedocsext/theme/templates/projects/settings_basics_form.html
- readthedocsext/theme/templates/projects/translation_list.html
Matches readthedocs/readthedocs.org#11169
> Project: merge basic and advanced forms

- readthedocsext/theme/templates/corporate/support.html
- readthedocsext/theme/templates/support/error.html
- readthedocsext/theme/templates/support/index.html
- readthedocsext/theme/templates/support/success.html
See #305 for screenshots.
- Fixes #305
> Fix support form bugs, add missing pages

- readthedocsext/theme/templates/socialaccount/snippets/provider_list.html
Ref https://github.com/readthedocs/readthedocs.org/pull/11262/
> Allauth: don't list SAML integrations

- readthedocsext/theme/templates/includes/header.html
Don't show if the user is not authenticated. I made the other changes in #299 to
improve the UX of this link, but it hurt performance. It's worth revisiting
later though, so I'll leave this open.
- Refs #299
> Fix organization nav link

- readthedocsext/theme/templates/account/login.html
- readthedocsext/theme/templates/semantic-ui/errors.html
> Fix a number of display issues with login view

- readthedocsext/theme/templates/base.html
Closes https://github.com/readthedocs/readthedocs-corporate/issues/1789
> Impersonate: add link to stop impersonating the user

- readthedocsext/theme/templates/projects/partials/header.html
- readthedocsext/theme/templatetags/ext_theme_tags.py
Allow us to quickly know the spam score of the project and what are their matching rules.
> Staff: show spam info

- readthedocsext/theme/templates/projects/import_config.html
Related https://github.com/readthedocs/ext-theme/issues/373
> Update copy when adding a project

- readthedocsext/theme/templates/errors/401.html
- readthedocsext/theme/templates/errors/proxito/401.html
Similar to https://github.com/readthedocs/ext-theme/pull/384, this is just a placeholder for now.
> Use custom 401 page for proxito

- readthedocsext/theme/templates/projects/partials/dashboard/example-projects.html
- readthedocsext/theme/templates/projects/partials/dashboard/ruby-support.html
- readthedocsext/theme/templates/projects/partials/dashboard/security-logs.html
> Add missing closing `div`s that break the footer

- readthedocsext/theme/templates/builds/build_detail.html
- readthedocsext/theme/templates/builds/includes/build_name.html
- readthedocsext/theme/templates/builds/partials/version_list.html
- readthedocsext/theme/templates/includes/elements/chips/version.html
> Versions: update GET attribute for filtering versions

- readthedocsext/theme/templates/account/login.html
- readthedocsext/theme/templates/account/saml.html
Needs https://github.com/readthedocs/readthedocs-corporate/pull/1824
Closes https://github.com/readthedocs/readthedocs-corporate/issues/1783
>  SAML: add login button 

- readthedocsext/theme/templates/account/login.html
Forgot that this template is shared with community...
> Login: don't show single sign-on options on community

- readthedocsext/theme/templates/projects/edit_base.html
Follows readthedocs/readthedocs.org#11453
> Addons: reframe it as "New" instead of "Beta"

- readthedocsext/theme/templates/projects/addons_form.html
Related https://github.com/readthedocs/ext-theme/pull/428
> Addons: remove beta notification and add documentation link

- readthedocsext/theme/templates/projects/integration_webhook_detail.html
> Integrations: use input elements for URL and secret

- readthedocsext/theme/templates/socialaccount/partials/social_account_list.html
Closes https://github.com/readthedocs/readthedocs-corporate/issues/1019
Needs https://github.com/readthedocs/readthedocs.org/pull/11503
> Social accounts: disable disconnect button if the account can't be disconnected

- readthedocsext/theme/templates/projects/partials/edit/automation_rule_list.html
- readthedocsext/theme/templates/projects/partials/edit/redirect_list.html
- Add a robot icon to automation rules
- Make the redirect item clickable
- Add an icon to configure automation rules
All of them follow the same consistency pattern across these submenus.
> Follow convetions from other pages

- readthedocsext/theme/templates/organizations/settings/saml.html
- readthedocsext/theme/templates/organizations/settings/sso_edit.html
- readthedocsext/theme/templates/projects/integration_webhook_detail.html
- readthedocsext/theme/templates/projects/keys_detail.html
- readthedocsext/theme/templates/projects/temporary_access_form.html
I split this PR in 2 commits to make it easier to review.
Closes #433
> Standardize copy buttons

- readthedocsext/theme/templates/profiles/private/advertising_profile.html
> Fix tests for real

- readthedocsext/theme/templates/projects/temporary_access_form.html
Found this one while running tests at https://github.com/readthedocs/readthedocs-corporate/pull/1807/ :D
> Fix endblock

- readthedocsext/theme/templates/projects/import_organization_team.html
Required by https://github.com/readthedocs/readthedocs-corporate/pull/1851
> Add project: template to select Organization and Team step

- readthedocsext/theme/templates/builds/partials/build_list.html
> Build list: protect us against builds without versions

- .djlintrc
- readthedocsext/theme/templates/builds/partials/build_list.html
Make `custom_html` lint rule more generic.
> djlint: update rules

- readthedocsext/theme/templates/builds/build_detail.html
- readthedocsext/theme/templates/builds/partials/build_list.html
- readthedocsext/theme/templates/projects/partials/project_list.html
> Fix more issues with URL resolution and null version builds

- readthedocsext/theme/templates/organizations/settings/saml.html
Matches https://github.com/readthedocs/readthedocs-corporate/pull/1872
> SAML: list application username in the config

- readthedocsext/theme/templates/includes/crud/table_list.html
- readthedocsext/theme/templates/organizations/includes/feature_disabled.html
- readthedocsext/theme/templates/organizations/settings/saml.html
- readthedocsext/theme/templates/organizations/settings/security_log.html
- readthedocsext/theme/templates/projects/domain_list.html
- readthedocsext/theme/templates/projects/partials/edit/domain_list.html
- readthedocsext/theme/templates/projects/partials/edit/search_query_list.html
- readthedocsext/theme/templates/projects/partials/edit/traffic_list.html
- readthedocsext/theme/templates/projects/search_analytics.html
- readthedocsext/theme/templates/projects/traffic_analytics.html
Use a callout and disable the page content if the feature is disabled. This
shows the full view but in a disabled state.
Changes are in 1314b79
- Fixes #291
> Unify disabled feature upgrade patterns

- readthedocsext/theme/templates/acl/shared_password_required.html
- Requires https://github.com/readthedocs/readthedocs-corporate/pull/1882
> Avoid using next, rely on application context data instead

- readthedocsext/theme/templates/includes/footer.html
> Footer: remove PagerDuty

- readthedocsext/theme/templates/account/password_change.html
- readthedocsext/theme/templates/mfa/base_manage.html
- readthedocsext/theme/templates/mfa/index.html
- readthedocsext/theme/templates/profiles/base_edit.html
> Account settings: link to 2FA page

- readthedocsext/theme/templates/includes/crud/remove_button.html
- readthedocsext/theme/templates/projects/partials/edit/domain_list.html
- readthedocsext/theme/templates/projects/settings_basics_form.html
- Closes https://github.com/readthedocs/ext-theme/issues/429
- Closes https://github.com/readthedocs/readthedocs.org/issues/11242
> Domain: show warning in a modal when deleting domain

- readthedocsext/theme/templates/builds/build_detail.html
- readthedocsext/theme/templates/organizations/partials/header.html
- readthedocsext/theme/templates/profiles/base_edit.html
- readthedocsext/theme/templates/projects/base.html
- readthedocsext/theme/templates/projects/base_dashboard.html
- readthedocsext/theme/templates/projects/partials/announcements/new-dashboard.html
- Add new dashboard announcement template
- Fix issues around spacing of top notifications
- Drop unused block on build detail page
1cfe710 is a linting step
----
- Refs https://github.com/readthedocs/readthedocs.org/pull/11543
- Refs https://github.com/readthedocs/readthedocs.org/issues/11209
- Refs https://github.com/readthedocs/website/pull/335
----
> Fixes and update for new dashboard pointers

- readthedocsext/theme/templates/projects/addons_form.html
Required by https://github.com/readthedocs/readthedocs.org/pull/11767/
> Remove addons field is not used anymore

- readthedocsext/theme/templates/organizations/partials/team_member_list.html
- readthedocsext/theme/templates/organizations/team_detail.html
Also fix team member user display.
- Fixes #416 
[Screencast From 2024-12-12 17-10-54.webm](https://github.com/user-attachments/assets/86caab83-34ea-464c-9e89-57470bf6ce51)
> Add remove button to team member listing view

- readthedocsext/theme/templates/invitations/partials/invitation_list.html
> Support past tense in invitations

- readthedocsext/theme/templates/organizations/organization_choose.html
> Add organization picker template

- readthedocsext/theme/templates/socialaccount/snippets/provider_list.html
ref https://github.com/readthedocs/readthedocs.org/pull/11892
> Social accounts: link Bitbucket to new dashboard

- readthedocsext/theme/templates/socialaccount/snippets/provider_list.html
Ref https://github.com/readthedocs/readthedocs.org/pull/12020
> Don't list GitHub App provider

- readthedocsext/theme/templates/includes/header.html
The icon is great, but it doesn't tell the user what it does.
> Add popup to support button

- readthedocsext/theme/templates/profiles/private/migrate_to_gh_app.html
- src/js/application/index.js
- src/js/profile/index.js
There were some display issues due to some of the element classes used,
I've simplified some of the is layout.
Also I've cleaned up the JS just a little to start. We have been using a
similar layout to views as `src/js/{app name}/index.js` or `src/js/{app
name}/migrate.js` etc.
> Fix some layout issues with elements used

- readthedocsext/theme/templates/organizations/settings/sso_edit.html
This templatetag isn't used at all
Ref https://github.com/readthedocs/readthedocs-corporate/pull/1993
> Remove corporate templatetag

- readthedocsext/theme/templates/profiles/partials/token_list.html
> Style button

- readthedocsext/theme/templates/account/password_set.html
> Override allauth template to style "Set password"

- readthedocsext/theme/templates/mfa/recovery_codes/index.html
This adds a toggle to view the codes. Feel free to reject this if you don't think it's necessary.
> Toggle to view 2FA recovery codes

- readthedocsext/theme/templates/projects/addons_form.html
Required by https://github.com/readthedocs/addons/issues/554
> Addons: add link previews selector field

- readthedocsext/theme/templatetags/ext_theme_tags.py
https://read-the-docs.sentry.io/issues/6867706588/?project=148442&query=is%3Aunresolved&referrer=issue-stream
> Fix unexpected logger
